//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BugTracker.Models
{
    using System;
    
    public partial class Bug
    {
        public string title { get; set; }
        public string submitter { get; set; }
        public string assignee { get; set; }
        public string severity { get; set; }
        public string state { get; set; }
        public System.DateTime submit_time { get; set; }
        public string version { get; set; }
        public Nullable<System.DateTime> fix_time { get; set; }
        public string description { get; set; }
        public string fix_description { get; set; }
    
        public virtual Assignee Assignee1 { get; set; }
        public virtual User User { get; set; }
        public virtual Image Image { get; set; }
    }
}
