//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BugTracker.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bug
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Bug()
        {
            this.Image = new HashSet<Image>();
        }
    
        public int id { get; set; }
        public string title { get; set; }
        public string submitter { get; set; }
        public string assignee { get; set; }
        public string severity { get; set; }
        public string state { get; set; }
        public System.DateTime submit_time { get; set; }
        public string version { get; set; }
        public Nullable<System.DateTime> fix_time { get; set; }
        public string description { get; set; }
        public string fix_description { get; set; }
    
        public virtual Assignee Assignee1 { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Image> Image { get; set; }
    }
}
